feign:
  hystrix:
    enabled: true

server:
  port: 9002
spring:
  messages:
    basename: static/i18n/messages
  application:
    name: ebuy-msg
  redis:
    port: 30014
    password: fsdFIG&fdsfbhJbZhgi!y21A
    host: redis.qcss.xyz
    timeout: 20000
    database: 0
    jedis:
      pool:
        # 最大空闲连接
        max-idle: 8
        # 最小空闲链接
        min-idle: 0
        # 最大连接数（负数表示没有限制）
        max-active: 8
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: 0
  datasource:
    url: jdbc:mysql://106.52.155.112:3306/ebuy?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: eBuy@123.com
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize: 5 # 初始化大小
      minIdle: 5 # 最小
      maxActive: 20 # 最大
      maxWait: 60000 # 获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true # 打开PSCache
      maxPoolPreparedStatementPerConnectionSize: 20 # 指定每个连接上PSCache的大小
      filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    hikari:
      validation-timeout: 60000
      idle-timeout: 60000
      connection-timeout: 60000
      max-lifetime: 60000
      #filters: stat,wall
      filter: # 单独配置 filter 能够执行批量sql
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)



mybatis:
  mapper-locations:
    - classpath*:/mappings/**/*.xml
    - classpath*:/**/dao/**/*.xml
  type-aliases-package: com.qy

eureka:
  instance:
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 5
    #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
    lease-expiration-duration-in-seconds: 10000
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
rocket:
  edebug: true
  web: true
  # 即时通讯服务
  im:
    enableMultipleConfig: true
    configs:
      config[0]:
        platform:
        active:
        wangyi:
          appKey:
          appSecret: